/**
 * Doc content builders for doc-generator.
 *
 * One builder per doc type: project-instructions, api, schema.
 * Each builder takes a list of source fragments and returns a markdown string.
 */

import { type SourceFragment, truncate, extractFirstParagraph } from './doc-generator-fs.js'

// ============================================================================
// Shared header helper
// ============================================================================

function docHeader(title: string, date: string, sourcesList: string): string[] {
  return [
    `# ${title}`,
    '',
    `> Auto-generated by crane-context on ${date}. Review and update as needed.`,
    `> Sources: ${sourcesList}`,
    '',
  ]
}

// ============================================================================
// Project-instructions sub-builders (extract complexity from main function)
// ============================================================================

function appendOverviewSection(sections: string[], readme: SourceFragment | undefined): void {
  sections.push('## Product Overview', '')
  if (readme) {
    const firstParagraph = extractFirstParagraph(readme.content)
    if (firstParagraph) sections.push(firstParagraph, '')
  }
}

function appendTechStackSection(sections: string[], pkgJson: SourceFragment | undefined): void {
  if (!pkgJson) return
  sections.push('## Tech Stack', '')
  try {
    const pkg = JSON.parse(pkgJson.content) as Record<string, unknown>
    const deps = pkg['dependencies']
    if (Array.isArray(deps) && deps.length > 0) {
      sections.push('**Key Dependencies:**', ...(deps as string[]).map((d) => `- ${d}`), '')
    }
  } catch {
    // ignore parse errors
  }
}

function appendVenturesTable(sections: string[], venturesJson: SourceFragment | undefined): void {
  if (!venturesJson) return
  sections.push('## Current Ventures', '')
  try {
    const config = JSON.parse(venturesJson.content) as Record<string, unknown>
    const ventures = (config['ventures'] ?? []) as Array<Record<string, unknown>>
    if (ventures.length === 0) return
    sections.push('| Code | Name | Status | BVM Stage |')
    sections.push('|------|------|--------|-----------|')
    for (const v of ventures) {
      const portfolio = v['portfolio'] as Record<string, unknown> | undefined
      const status = portfolio?.['status'] ?? 'unknown'
      const stage = portfolio?.['bvmStage'] ?? '-'
      sections.push(
        `| ${String(v['code'])} | ${String(v['name'])} | ${String(status)} | ${String(stage)} |`
      )
    }
    sections.push('')
  } catch {
    // skip if parse fails
  }
}

// ============================================================================
// Doc builders
// ============================================================================

export function buildProjectInstructions(
  ventureName: string,
  _venture: string,
  fragments: SourceFragment[],
  date: string,
  sourcesList: string
): string {
  const sections: string[] = docHeader(`${ventureName} - Project Instructions`, date, sourcesList)

  const claudeMd = fragments.find((f) => f.label === 'CLAUDE.md')
  const readme = fragments.find((f) => f.label === 'README.md')
  const pkgJson = fragments.find((f) => f.label === 'package.json')
  const docsProcess = fragments.find((f) => f.label === 'docs/process/')
  const venturesJson = fragments.find((f) => f.label === 'ventures.json')

  appendOverviewSection(sections, readme)
  appendTechStackSection(sections, pkgJson)

  if (claudeMd) {
    sections.push('## Development Instructions', '', truncate(claudeMd.content, 8000), '')
  }

  if (docsProcess) {
    sections.push('## Process Documentation', '', truncate(docsProcess.content, 4000), '')
  }

  appendVenturesTable(sections, venturesJson)

  return sections.join('\n')
}

export function buildApiDoc(
  ventureName: string,
  _venture: string,
  fragments: SourceFragment[],
  date: string,
  sourcesList: string
): string {
  const sections: string[] = docHeader(`${ventureName} - API Reference`, date, sourcesList)

  const openapi = fragments.find((f) => f.label === 'OpenAPI Spec')
  const routes = fragments.find((f) => f.label === 'Route Files')
  const tests = fragments.find((f) => f.label === 'Test Files (API-related)')

  if (openapi) {
    sections.push(
      '## API Specification',
      '',
      '```yaml',
      truncate(openapi.content, 10000),
      '```',
      ''
    )
  }

  if (routes) {
    sections.push(
      '## Route Definitions',
      '',
      'The following route files define the API endpoints:',
      '',
      '```typescript',
      truncate(routes.content, 15000),
      '```',
      ''
    )
  }

  if (tests) {
    sections.push(
      '## API Test Patterns',
      '',
      'Endpoint usage patterns from tests:',
      '',
      '```typescript',
      truncate(tests.content, 8000),
      '```',
      ''
    )
  }

  return sections.join('\n')
}

export function buildSchemaDoc(
  ventureName: string,
  _venture: string,
  fragments: SourceFragment[],
  date: string,
  sourcesList: string
): string {
  const sections: string[] = docHeader(`${ventureName} - Database Schema`, date, sourcesList)

  const migrations = fragments.find((f) => f.label === 'Migration Files')
  const schema = fragments.find((f) => f.label === 'Schema/Model Files')
  const wrangler = fragments.find((f) => f.label === 'Wrangler Config')

  if (wrangler) {
    sections.push(
      '## Database Bindings',
      '',
      'From wrangler.toml:',
      '',
      '```toml',
      truncate(wrangler.content, 3000),
      '```',
      ''
    )
  }

  if (migrations) {
    sections.push('## Migrations', '', '```sql', truncate(migrations.content, 20000), '```', '')
  }

  if (schema) {
    sections.push(
      '## Schema Definitions',
      '',
      '```typescript',
      truncate(schema.content, 10000),
      '```',
      ''
    )
  }

  return sections.join('\n')
}
