/**
 * Tests for doc-generator.ts
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { existsSync, readFileSync, readdirSync, statSync } from 'fs'

vi.mock('fs')

describe('doc-generator', () => {
  beforeEach(() => {
    vi.mocked(existsSync).mockReturnValue(false)
  })

  afterEach(() => {
    vi.clearAllMocks()
    vi.restoreAllMocks()
  })

  const getModule = async () => {
    vi.resetModules()
    return import('./doc-generator.js')
  }

  describe('generateDoc', () => {
    it('returns null when no sources are available', async () => {
      const { generateDoc } = await getModule()

      const result = generateDoc(
        'vc-project-instructions.md',
        'vc',
        'Venture Crane',
        ['claude_md', 'readme'],
        '/fake/repo'
      )

      expect(result).toBeNull()
    })

    it('generates project-instructions from CLAUDE.md', async () => {
      const { generateDoc } = await getModule()

      vi.mocked(existsSync).mockImplementation((path) => {
        return String(path).endsWith('CLAUDE.md')
      })

      vi.mocked(readFileSync).mockReturnValue(
        '# CLAUDE.md\n\nThis is the crane console project.\n\n## Stack\nTypeScript, Cloudflare Workers'
      )

      const result = generateDoc(
        'vc-project-instructions.md',
        'vc',
        'Venture Crane',
        ['claude_md'],
        '/fake/repo'
      )

      expect(result).not.toBeNull()
      expect(result!.title).toBe('Venture Crane - Project Instructions')
      expect(result!.content).toContain('Venture Crane')
      expect(result!.content).toContain('Auto-generated by crane-context')
      expect(result!.content).toContain('Development Instructions')
      expect(result!.sources_read).toContain('CLAUDE.md')
    })

    it('generates project-instructions from package.json', async () => {
      const { generateDoc } = await getModule()

      vi.mocked(existsSync).mockImplementation((path) => {
        return String(path).endsWith('package.json')
      })

      vi.mocked(readFileSync).mockReturnValue(
        JSON.stringify({
          name: '@venturecrane/crane-console',
          description: 'Crane console app',
          version: '1.0.0',
          dependencies: { react: '18', next: '14' },
          devDependencies: { typescript: '5' },
          scripts: { build: 'tsc', test: 'vitest' },
        })
      )

      const result = generateDoc(
        'vc-project-instructions.md',
        'vc',
        'Venture Crane',
        ['package_json'],
        '/fake/repo'
      )

      expect(result).not.toBeNull()
      expect(result!.content).toContain('Tech Stack')
      expect(result!.content).toContain('react')
      expect(result!.content).toContain('next')
    })

    it('generates api doc from route files', async () => {
      const { generateDoc } = await getModule()

      // Mock directory structure with route files
      vi.mocked(existsSync).mockImplementation((path) => {
        const p = String(path)
        return p.includes('/src/routes') || p.includes('/workers')
      })

      vi.mocked(readdirSync).mockImplementation((dirPath) => {
        const p = String(dirPath)
        if (p.endsWith('/src/routes')) {
          return ['index.ts', 'users.ts'] as any
        }
        return [] as any
      })

      vi.mocked(statSync).mockReturnValue({
        isDirectory: () => false,
        isFile: () => true,
      } as any)

      vi.mocked(readFileSync).mockReturnValue(
        'export function GET() { return new Response("ok"); }'
      )

      const result = generateDoc('vc-api.md', 'vc', 'Venture Crane', ['route_files'], '/fake/repo')

      expect(result).not.toBeNull()
      expect(result!.title).toBe('Venture Crane - API Reference')
      expect(result!.content).toContain('Route Definitions')
    })

    it('generates schema doc from migrations', async () => {
      const { generateDoc } = await getModule()

      vi.mocked(existsSync).mockImplementation((path) => {
        const p = String(path)
        return p.includes('/migrations') || p.includes('/workers')
      })

      vi.mocked(readdirSync).mockImplementation((dirPath) => {
        const p = String(dirPath)
        if (p.endsWith('/migrations')) {
          return ['001_init.sql', '002_users.sql'] as any
        }
        if (p.endsWith('/workers')) {
          return ['crane-context'] as any
        }
        return [] as any
      })

      vi.mocked(statSync).mockReturnValue({
        isDirectory: () => false,
        isFile: () => true,
      } as any)

      vi.mocked(readFileSync).mockReturnValue(
        'CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);'
      )

      const result = generateDoc(
        'vc-schema.md',
        'vc',
        'Venture Crane',
        ['migrations'],
        '/fake/repo'
      )

      expect(result).not.toBeNull()
      expect(result!.title).toBe('Venture Crane - Database Schema')
      expect(result!.content).toContain('Migrations')
      expect(result!.content).toContain('CREATE TABLE')
    })

    it('handles unknown doc types gracefully', async () => {
      const { generateDoc } = await getModule()

      const result = generateDoc(
        'vc-unknown.md',
        'vc',
        'Venture Crane',
        ['claude_md'],
        '/fake/repo'
      )

      expect(result).toBeNull()
    })
  })
})
