# Venture Crane Standard CI Workflow
#
# Copy this file to .github/workflows/ci.yml in your venture repo
# Customize the paths and commands for your specific project
#
# Version: 1.0
# Last Updated: 2026-01-31

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ==========================================================================
  # Typecheck & Lint
  # ==========================================================================
  check:
    name: Typecheck & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Frontend (if exists)
      - name: Install frontend dependencies
        run: npm ci
        working-directory: .
        continue-on-error: true

      - name: Typecheck frontend
        run: npx tsc --noEmit
        working-directory: .
        continue-on-error: true

      - name: Lint frontend
        run: npm run lint
        working-directory: .
        continue-on-error: true

      # API Worker (if exists)
      - name: Install API dependencies
        run: npm ci
        working-directory: workers/{venture}-api
        continue-on-error: true

      - name: Typecheck API
        run: npx tsc --noEmit
        working-directory: workers/{venture}-api
        continue-on-error: true

  # ==========================================================================
  # Tests
  # ==========================================================================
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # API Worker tests
      - name: Install API dependencies
        run: npm ci
        working-directory: workers/{venture}-api

      - name: Run API tests
        run: npm test
        working-directory: workers/{venture}-api

      # Frontend tests (if configured)
      - name: Install frontend dependencies
        run: npm ci
        working-directory: .
        continue-on-error: true

      - name: Run frontend tests
        run: npm test -- --passWithNoTests
        working-directory: .
        continue-on-error: true

  # ==========================================================================
  # Build Verification
  # ==========================================================================
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Frontend build
      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build
        env:
          # Add required env vars for build
          NEXT_PUBLIC_API_URL: https://example.workers.dev

  # ==========================================================================
  # Deploy (on main branch only)
  # ==========================================================================
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: workers/{venture}-api

      - name: Deploy to Cloudflare
        run: npx wrangler deploy
        working-directory: workers/{venture}-api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

# ==========================================================================
# CUSTOMIZATION NOTES
# ==========================================================================
#
# 1. Replace {venture}-api with your actual worker directory name
#
# 2. Add required secrets to GitHub:
#    - CLOUDFLARE_API_TOKEN: For worker deployments
#
# 3. Customize the frontend build env vars as needed
#
# 4. For Vercel-hosted frontends, frontend deploy is automatic via Vercel
#    GitHub integration - no workflow step needed
#
# 5. Add additional jobs as needed:
#    - E2E tests with Playwright
#    - a11y audits with axe-core
#    - Database migrations
#
# ==========================================================================
