#!/usr/bin/env node
/**
 * scripts/inject-version.mjs
 *
 * Plan v3.1 §D.1. Build-time version metadata injection for Cloudflare
 * Workers in this monorepo. Writes `src/generated/build-info.ts` in the
 * target worker directory with commit SHA, build timestamp, and
 * schema hash (for crane-context).
 *
 * Invoked via each worker's wrangler.toml [build] command:
 *
 *   [build]
 *   command = "node ../../scripts/inject-version.mjs --service=crane-context"
 *
 * The generated build-info.ts is imported by the worker's /version
 * endpoint (see workers/<worker>/src/endpoints/version.ts).
 *
 * CODEOWNERS note: this file is owned by the captain. It is the source
 * of truth for the deployed-commit claim that invariant I-1 enforces.
 * Changes require captain review (see CODEOWNERS).
 *
 * Supply-chain hardening:
 * - Refuses to run if GITHUB_SHA env var is set (CI context) and
 *   disagrees with `git rev-parse HEAD`. This prevents a compromised
 *   CI workflow from forcing a fake commit SHA into build-info.
 * - Only reads the committed migrations/schema.hash for crane-context;
 *   never recomputes hashes at build time.
 *
 * Usage:
 *   node scripts/inject-version.mjs --service=crane-context
 *   node scripts/inject-version.mjs --service=crane-watch
 *   node scripts/inject-version.mjs --service=crane-mcp-remote
 */

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..')

// ---- Args ----
const args = process.argv.slice(2)
let service = null
for (const a of args) {
  if (a.startsWith('--service=')) {
    service = a.slice('--service='.length)
  }
}
if (!service) {
  console.error('error: --service=<worker-name> is required')
  console.error(
    'usage: node scripts/inject-version.mjs --service=crane-context|crane-watch|crane-mcp-remote'
  )
  process.exit(2)
}

const ALLOWED_SERVICES = ['crane-context', 'crane-watch', 'crane-mcp-remote']
if (!ALLOWED_SERVICES.includes(service)) {
  console.error(`error: unknown service '${service}'. Allowed: ${ALLOWED_SERVICES.join(', ')}`)
  process.exit(2)
}

const WORKER_DIR = join(REPO_ROOT, 'workers', service)
const GENERATED_DIR = join(WORKER_DIR, 'src', 'generated')
const BUILD_INFO_PATH = join(GENERATED_DIR, 'build-info.ts')

if (!existsSync(WORKER_DIR)) {
  console.error(`error: worker directory not found: ${WORKER_DIR}`)
  process.exit(2)
}

// ---- Compute commit SHA ----
let commit
try {
  commit = execSync('git rev-parse HEAD', { cwd: REPO_ROOT, encoding: 'utf8' }).trim()
} catch (err) {
  console.error('error: `git rev-parse HEAD` failed (not a git repo?)')
  console.error(err.message)
  process.exit(2)
}

// ---- Supply-chain guard ----
// If GITHUB_SHA is set (CI context) and disagrees with `git rev-parse HEAD`,
// something is wrong. Refuse to write a potentially-fake commit SHA.
if (process.env.GITHUB_SHA && process.env.GITHUB_SHA !== commit) {
  console.error('error: GITHUB_SHA env var disagrees with `git rev-parse HEAD`')
  console.error(`  GITHUB_SHA: ${process.env.GITHUB_SHA}`)
  console.error(`  git HEAD:   ${commit}`)
  console.error(
    'This usually indicates a CI-side commit SHA mismatch. Refusing to generate build-info.'
  )
  process.exit(2)
}

// ---- Build timestamp ----
const buildTimestamp = new Date().toISOString()

// ---- Schema hash (crane-context only) ----
let schemaHash = null
if (service === 'crane-context') {
  const hashPath = join(WORKER_DIR, 'migrations', 'schema.hash')
  if (!existsSync(hashPath)) {
    console.error(`error: ${hashPath} not found`)
    console.error('Expected the H-2 schema.hash to be committed. Run:')
    console.error('  bash workers/crane-context/scripts/compute-schema-hash.sh --update')
    process.exit(2)
  }
  schemaHash = readFileSync(hashPath, 'utf8').trim()
  if (!/^[0-9a-f]{64}$/i.test(schemaHash)) {
    console.error(`error: ${hashPath} does not contain a valid SHA-256 hex digest`)
    console.error(`  read: ${schemaHash}`)
    process.exit(2)
  }
}

// ---- Generate build-info.ts ----
const safeService = JSON.stringify(service)
const safeCommit = JSON.stringify(commit)
const safeCommitShort = JSON.stringify(commit.slice(0, 7))
const safeBuildTimestamp = JSON.stringify(buildTimestamp)
const safeSchemaHash = schemaHash ? JSON.stringify(schemaHash) : 'undefined'

const content = `/**
 * AUTO-GENERATED — DO NOT EDIT.
 *
 * This file is generated by scripts/inject-version.mjs at build time
 * (invoked by wrangler.toml [build] command) and imported by the
 * /version endpoint. See plan v3.1 §D.1.
 *
 * The hash of this file should change on every deploy. If two deploys
 * produce the same content, it means nothing changed since the last
 * build (which is fine for re-deploys) OR the injection script failed
 * silently (which is not — the CODEOWNERS rule on this file catches that).
 */

export interface BuildInfo {
  readonly service: 'crane-context' | 'crane-watch' | 'crane-mcp-remote'
  readonly commit: string
  readonly commit_short: string
  readonly build_timestamp: string
  readonly schema_hash: string | undefined
}

export const BUILD_INFO: BuildInfo = {
  service: ${safeService} as const,
  commit: ${safeCommit},
  commit_short: ${safeCommitShort},
  build_timestamp: ${safeBuildTimestamp},
  schema_hash: ${safeSchemaHash},
} as const
`

// ---- Write ----
if (!existsSync(GENERATED_DIR)) {
  mkdirSync(GENERATED_DIR, { recursive: true })
}
writeFileSync(BUILD_INFO_PATH, content, 'utf8')

console.log(`✓ inject-version: ${service}`)
console.log(`  commit:          ${commit}`)
console.log(`  build_timestamp: ${buildTimestamp}`)
if (schemaHash) {
  console.log(`  schema_hash:     ${schemaHash}`)
}
console.log(`  written to:      ${BUILD_INFO_PATH}`)
